[package]
name = "realearn-rs"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"

[workspace]
members = [
    "swell-ui",
    "rx-util",
    "helgoboss-learn"
]

[features]
generate = []

[dependencies]
reaper-high = { git = "https://github.com/helgoboss/reaper-rs", features = ["serde"] }
reaper-medium= { git = "https://github.com/helgoboss/reaper-rs", features = ["serde"] }
reaper-low = { git = "https://github.com/helgoboss/reaper-rs" }
swell-ui = { path = "swell-ui" }
rx-util = { path = "rx-util" }
helgoboss-midi = { git = "https://github.com/helgoboss/helgoboss-midi", branch = "master", features = ["serde", "serde_repr"] }
helgoboss-learn = { path = "helgoboss-learn", features = ["serde", "serde_repr"] }
c_str_macro = "1.0.2"
vst = { git = "https://github.com/helgoboss/vst-rs", branch = "feature/custom-support-variant" }
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.5"
validator = "0.10.0"
validator_derive = "0.10"
derive_more = "0.99.5"
lazycell = "1.2"
enum-iterator = "0.6.0"
num_enum = "0.5.0"
scopeguard = "1.1.0"
crossbeam-channel = "0.4"
uuid = { version = "0.8.1", features = ["v4"] }
slog = "2.5.2"

[build-dependencies]
bindgen = "0.52.0"
cc = "1.0.50"
embed-resource = "1.3"

[lib]
name = "realearn_rs"
crate-type = ["cdylib"]