[workspace]
members = [
    "main",
    "rx-util",
    "swell-ui",
    # Will probably excluded from the workspace in future
    "main/lib/helgoboss-learn"
]

[profile.release]
# This is important for having line numbers in bug reports.
debug = true

[patch.crates-io]
# TODO-low-wait
# I absolutely need Flutter to be able to connect with ReaLearn based on a LAN IP address. Without this hack, Flutter
# will fail to connect with a TLSV1_ALERT_DECODE_ERROR. As soon as webpki #54 is closed and Warp/Rustls has updated
# the dependency, we should remove this!
webpki = { git = "https://github.com/helgoboss/webpki.git", branch = "workaround/54-alert-decode-error" }