[package]
name = "realearn-rs"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"

[features]
generate = []

[dependencies]
reaper-high = { path = "../reaper-rs/main/high" }
reaper-medium= { path = "../reaper-rs/main/medium" }
reaper-low = { version = "0.1.0", path = "../reaper-rs/main/low" }
helgoboss-midi = { version = "0.1.0", path = "../helgoboss-midi-rs" }
helgoboss-learn = { path = "../helgoboss-learn-rs" }
c_str_macro = "1.0.2"
vst = { git = "https://github.com/helgoboss/vst-rs", branch = "feature/custom-support-variant" }
rxrust = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.5"
validator = "0.10.0"
validator_derive = "0.10"

[build-dependencies]
bindgen = "0.52.0"
cc = "1.0.50"
embed-resource = "1.3"

[lib]
name = "realearn_rs"
crate-type = ["cdylib"]