[package]
name = "realearn"
version = "1.12.0-pre1"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"
license = "LGPL-3.0"

[features]
generate = []

[dependencies]
reaper-high = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
reaper-medium= { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
#reaper-high = { path = "../../reaper-rs/main/high", features = ["serde"] }
#reaper-medium= { path = "../../reaper-rs/main/medium", features = ["serde"] }
#reaper-low = { path = "../../reaper-rs/main/low" }
swell-ui = { path = "../swell-ui" }
rx-util = { path = "../rx-util" }
helgoboss-midi = { git = "https://github.com/helgoboss/helgoboss-midi", branch = "master", features = ["serde", "serde_repr"] }
# In future (when helgoboss-learn has matured), this will become a crates.io dependency
helgoboss-learn = { path = "lib/helgoboss-learn", features = ["serde", "serde_repr"] }
c_str_macro = "1.0.2"
vst = { git = "https://github.com/helgoboss/vst-rs", branch = "feature/custom-support-variant" }
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.5"
validator = "0.10.0"
validator_derive = "0.10"
derive_more = "0.99.5"
lazycell = "1.2"
enum-iterator = "0.6.0"
num_enum = "0.5.0"
scopeguard = "1.1.0"
crossbeam-channel = "0.4"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
slog = "2.5.2"
clipboard = "0.5.0"
once_cell = "1.4.0"
wrap-debug = "0.1.1"
chrono = "0.4.11"
smallvec = "1.4.0"
backtrace = "0.3"
regex = "1"
enum-map = "0.6.3"
# For generating controller file names from controller names
slug = "0.1.4"
# For generating random session IDs
nanoid = "0.3.0"
# For web server (e.g. for projection)
futures = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["rt-core", "sync"] }
warp = { version = "0.2", features = ["tls"] }
# For rendering projection setup HTML page
web-view = "0.6.3"
#web-view = { git = "https://github.com/helgoboss/web-view.git", branch = "workaround/issue-244-build-error" }
# For generating projection QR code
qrcode = { version = "0.11" }
# For rendering projection QR code to PNG
image = "0.22"
# For generating self-signed certificate for projection web server
rcgen = "0.8.5"
# For showing different ways of connecting to this computer (projection feature)
dns-lookup = "1.0.4"
hostname = "^0.3"
# For rendering projection setup HTML page template
askama = "0.8"
# For generating projection QR code data URI
base64 = "0.13.0"
# For persisting app configuration
serde_ini = "0.2.0"
# For opening companion app in local browser
webbrowser = "0.5.5"
# For adding firewall rules
runas = "0.2.1"
# For building URls, e.g. companion web app URL
url = "2.1.1"
# For grouping mappings by virtual control elements
itertools = "0.9"
# For being able to log to terminal
slog-term = "2.5.0"
# For being able to configure logging via environment variable RUST_LOG
slog-envlogger = "2.2.0"
# Using envlogger also requires async (logging happens in dedicated thread, global, not per ReaLearn instance)
slog-async = "2.5.0"
# We want to forward standard logging messages to slog (e.g. warp logging is interesting)
slog-stdlog = "4.1.0"
# If we want to forward, we also need a global logger
slog-scope = "4.3.0"

[build-dependencies]
built = { version = "0.4.3", features = ["git2", "chrono"] }
bindgen = "0.52.0"
cc = "1.0.50"
embed-resource = "1.3"

[lib]
name = "realearn"
crate-type = ["cdylib"]