[package]
name = "realearn"
version = "1.12.0-pre1"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"
license = "LGPL-3.0"

[features]
generate = []

[dependencies]
reaper-high = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
reaper-medium= { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
#reaper-high = { path = "../../reaper-rs/main/high", features = ["serde"] }
#reaper-medium= { path = "../../reaper-rs/main/medium", features = ["serde"] }
#reaper-low = { path = "../../reaper-rs/main/low" }
swell-ui = { path = "../swell-ui" }
rx-util = { path = "../rx-util" }
helgoboss-midi = { git = "https://github.com/helgoboss/helgoboss-midi", branch = "master", features = ["serde", "serde_repr"] }
# In future (when helgoboss-learn has matured), this will become a crates.io dependency
helgoboss-learn = { path = "lib/helgoboss-learn", features = ["serde", "serde_repr"] }
c_str_macro = "1.0.2"
vst = { git = "https://github.com/helgoboss/vst-rs", branch = "feature/custom-support-variant" }
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1.5"
validator = "0.10.0"
validator_derive = "0.10"
derive_more = "0.99.5"
lazycell = "1.2"
enum-iterator = "0.6.0"
num_enum = "0.5.0"
scopeguard = "1.1.0"
crossbeam-channel = "0.4"
uuid = { version = "0.8.1", features = ["v4"] }
slog = "2.5.2"
clipboard = "0.5.0"
once_cell = "1.4.0"
wrap-debug = "0.1.1"
chrono = "0.4.11"
smallvec = "1.4.0"
backtrace = "0.3"
regex = "1"
enum-map = "0.6.3"
slug = "0.1.4"
nanoid = "0.3.0"
futures = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["rt-core", "sync"] }
warp = "0.2"

[build-dependencies]
built = { version = "0.4.3", features = ["git2", "chrono"] }
bindgen = "0.52.0"
cc = "1.0.50"
embed-resource = "1.3"

[lib]
name = "realearn"
crate-type = ["cdylib"]