[package]
name = "realearn"
version = "2.8.2"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0"

[features]
default = ["prometheus"]

# Regenerate bindings (for dialog resource IDs and EEL functions)
generate = []

# Expose metrics endpoint in prometheus format (via projection server)
prometheus = ["serde_prometheus"]

[dependencies]
 reaper-rx = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
 reaper-high = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
 reaper-medium = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master", features = ["serde"] }
 reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
#reaper-rx = { path = "../../reaper-rs/main/rx" }
#reaper-high = { path = "../../reaper-rs/main/high", features = ["serde"] }
#reaper-medium= { path = "../../reaper-rs/main/medium", features = ["serde"] }
#reaper-low = { path = "../../reaper-rs/main/low" }
swell-ui = { path = "../swell-ui" }
rx-util = { path = "../rx-util" }
helgoboss-midi = { version = "0.2", features = ["serde", "serde_repr"] }
# In future (when helgoboss-learn has matured), this will become a crates.io dependency
helgoboss-learn = { path = "lib/helgoboss-learn", features = ["serde", "serde_repr", "reaper-low"] }
c_str_macro = "1.0.2"
vst = "0.2.1"
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_repr = "0.1.5"
validator = "0.10.0"
validator_derive = "0.10"
derive_more = "0.99.5"
lazycell = "1.2"
enum-iterator = "0.6.0"
num_enum = "0.5.0"
scopeguard = "1.1.0"
crossbeam-channel = "0.4"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
slog = "2.5.2"
clipboard = "0.5.0"
once_cell = "1.4.0"
# For deriving Debug even HostCallback doesn't implement it
wrap-debug = "0.1.1"
chrono = "0.4.11"
smallvec = "1.4.0"
backtrace = "0.3"
regex = "1"
enum-map = "0.6.3"
# For generating controller file names from controller names
slug = "0.1.4"
# For generating random session IDs
nanoid = "0.3.0"
# For web server (e.g. for projection)
futures = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = ["rt-core", "rt-threaded", "sync", "macros"] }
warp = { version = "0.2", features = ["tls"] }
# For generating projection QR code
qrcode = { version = "0.11" }
# For rendering projection QR code to PNG
image = "0.22"
# For generating self-signed certificate for projection web server
rcgen = "0.8.5"
# For showing different ways of connecting to this computer (projection feature)
dns-lookup = "1.0.4"
hostname = "^0.3"
# For rendering projection setup HTML page template
askama = "0.8"
# For persisting app configuration
serde_ini = "0.2.0"
# For opening projection setup page and companion app in local browser
webbrowser = "0.5.5"
# For writing generated projection setup page to disk
tempfile = "3.1.0"
# For adding firewall rules
runas = "0.2.1"
# For building URls, e.g. companion web app URL
url = "2.1.1"
# For grouping mappings by virtual control elements and grouping outgoing OSC messages by device
itertools = "0.9"
# For being able to configure logging via environment variable RUST_LOG
env_logger = "0.8.2"
# We want to forward slog logging to standard logging
slog-stdlog = "4.1.0"
# To be able to yield to main thread in async functions
futures-timer = "3.0.2"
# To open user guide in local PDF app
open = "1"
# For exposing metrics in Prometheus format
serde_prometheus = { version = "0.1.5", optional = true }
# In projection server, we must be able to handle controller IDs with special characters
percent-encoding = "2.1.0"
# For comparing ReaLearn versions in order to determine if preset migration is necessary
semver = "0.9.0"
# Maybe better asynchronous channel than in futures or tokio (basically the async version of crossbeam)
async-channel = "1.5.1"
# For displaying snapshot sizes
bytesize = "1.0.1"
# For checking if an FX has loaded a specific chunk
seahash = "4.1.0"
# For OSC
rosc = "0.4.2"
# For being able to (de)serialize using FromStr
serde_with = "1.6.4"
# For letting the user edit advanced mapping settings
edit = { git = "https://github.com/helgoboss/edit", branch = "realearn" }
# For parsing/formatting advanced mapping settings
serde_yaml = "0.8.17"
# For parsing hexadecimal data notation to byte vector (for system-exclusive lifecycle MIDI messages)
hex = "0.4.2"
# For evaluation of <Dynamic> formulas
fasteval = { version = "0.2.4", default-features = false }
# For wildcard support when using "By name" selector
wildmatch = "2.1.0"
# For creating HashSet literals for projection feedback and in unit tests
maplit = "1.0.2"
# For easier support of named virtual control elements
ascii = "1.0"
# For using bit flags in the reaper-rs API.
enumflags2 = { version = "^0.6", features = ["not_literal"] }
# For detecting undesired deallocation in real-time threads.
assert_no_alloc = "1.1.0"
# For deferring deallocation to main thread.
basedrop = "0.1.1"

[target.'cfg(windows)'.dependencies]
# For detecting the Windows version (to determine whether special charactes can be displayed)
sys-info = "0.7"

[build-dependencies]
# For making Git commit hash available to code
built = { version = "0.4.3", features = ["git2", "chrono"] }
# For generating bindings (for dialog resource IDs and EEL functions)
bindgen = "0.52.0"
# For compiling EEL and SWELL dialog resources
cc = "1.0.50"
# For embedding ResEdit files on Windows
embed-resource = "1.3"

[lib]
name = "realearn"
crate-type = ["cdylib"]