[package]
name = "swell-ui"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

[dependencies]
reaper-low = { git = "https://github.com/helgoboss/reaper-rs.git", branch = "master" }
#reaper-low = { path = "../../reaper-rs/main/low" }
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
rx-util = { path = "../rx-util" }
scopeguard = "1.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "uxtheme"] }
palette = "0.5"

[build-dependencies]
bindgen = "0.52.0"