[package]
name = "swell-ui"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"
build = "build.rs"

[features]
generate = []

[dependencies]
reaper-low = { path = "../reaper-rs/main/low" }
rxrust = { git = "https://github.com/helgoboss/rxRust", branch = "reaper-rs" }
rx-util = { path = "../rx-util" }
scopeguard = "1.1.0"

[build-dependencies]
bindgen = "0.52.0"