[package]
name = "realearn-csi"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"

[dependencies]
nom = "7.0.0"
helgoboss-midi = "0.3"
realearn-api = { path = "../api" }
derive_more = "0.99.16"