[package]
name = "realearn-api"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8.6"
serde_json = "1.0"
playtime-api = { path = "../playtime-api" }

[dev-dependencies]
mlua = { version = "0.7.3", features = ["vendored", "lua54", "serialize"] }