on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linux

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15
          override: true
      - name: Set up dependencies
        run: sudo apt-get install nasm xorg-dev libxcb-shape0-dev libxcb-render0-dev libxcb-xfixes0-dev
      - name: Compile EEL assembler code
        working-directory: lib/WDL/WDL/eel2
        run: make asm-nseel-x64.o
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: test-plug-ins
          path: target/debug/*.so