on:
  push:
    tags:
      - 'v*'

name: Create release

jobs:

  build-release-artifacts:
    name: Build artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        artifact: [windows-x86_64, windows-i686, macos-x86_64, linux-x86_64]
        include:
          - artifact: windows-x86_64
            os: windows-latest
            toolchain-suffix: x86_64-pc-windows-msvc
            lib-file-name: realearn.dll
          - artifact: windows-i686
            os: windows-latest
            toolchain-suffix: i686-pc-windows-msvc
            lib-file-name: realearn.dll
          - artifact: macos-x86_64
            os: macos-latest
            toolchain-suffix: x86_64-apple-darwin
            lib-file-name: librealearn.dylib
          - artifact: linux-x86_64
            os: ubuntu-latest
            toolchain-suffix: x86_64-unknown-linux-gnu
            lib-file-name: librealearn.so
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7 # This is relevant for macOS builds only
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15-${{ matrix.toolchain-suffix }}
          override: true
      - name: Install native Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install nasm xorg-dev libxcb-shape0-dev libxcb-render0-dev libxcb-xfixes0-dev
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/release/${{ matrix.lib-file-name }}

  create-release:
    name: Publish release
    needs: build-release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: ${{ contains(github.ref, 'pre') }}
      - name: Download artifacts from build job
        uses: actions/download-artifact@v2
      - name: Upload windows-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-x86_64/realearn.dll
          asset_name: realearn-${{ github.ref }}-windows-x86_64.dll
          asset_content_type: application/octet-stream
      - name: Upload windows-i686 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-i686/realearn.dll
          asset_name: realearn-${{ github.ref }}-windows-i686.dll
          asset_content_type: application/octet-stream
      - name: Upload macos-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-x86_64/librealearn.dylib
          asset_name: realearn-${{ github.ref }}-macos-x86_64.vst.dylib
          asset_content_type: application/octet-stream
      - name: Upload linux-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-x86_64/librealearn.so
          asset_name: realearn-${{ github.ref }}-linux-x86_64.so
          asset_content_type: application/octet-stream