on:
  create:
    ref_type: tag
    ref: 'v*'

name: Create release

jobs:

  build-release-artifacts:
    name: Build artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - artifact: windows-x86_64
            os: windows-latest
            toolchain-suffix: x86_64-pc-windows-msvc
            lib-file-name: realearn.dll
          - artifact: windows-i686
            os: windows-latest
            toolchain-suffix: i686-pc-windows-msvc
            lib-file-name: realearn.dll
          - artifact: macos-x86_64
            os: macos-latest
            toolchain-suffix: x86_64-apple-darwin
            lib-file-name: librealearn.dylib
#          - artifact: linux-x86_64
#            os: ubuntu-latest
#            toolchain-suffix: x86_64-unknown-linux-gnu
#            lib-file-name: librealearn.so
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7 # This is relevant for macOS builds only
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15-${{ matrix.toolchain-suffix }}
          override: true
      - name: Install native Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install nasm xorg-dev libxcb-shape0-dev libxcb-render0-dev libxcb-xfixes0-dev libwebkit2gtk-4.0
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Strip debug symbols from Linux binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          cp target/release/librealearn.so target/release/librealearn-debug.so
          strip target/release/librealearn.so
      - name: Upload plug-in to artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/release/${{ matrix.lib-file-name }}
      - name: Upload Windows debug symbols to artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/release/realearn.pdb
      - name: Upload macOS debug symbols to artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/release/deps/librealearn.dylib.dSYM/
      - name: Upload Linux debug symbols to artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: target/release/librealearn-debug.so

  create-release:
    name: Publish release
    needs: build-release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          release_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          draft: true
          prerelease: ${{ contains(github.ref, 'pre') }}
      - name: Download artifacts from build job
        uses: actions/download-artifact@v2
      - name: Upload windows-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-x86_64/realearn.dll
          asset_name: realearn-windows-x86_64.dll
          asset_content_type: application/octet-stream
      - name: Upload windows-i686 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-i686/realearn.dll
          asset_name: realearn-windows-i686.dll
          asset_content_type: application/octet-stream
      - name: Upload macos-x86_64 release artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos-x86_64/librealearn.dylib
          asset_name: realearn-macos-x86_64.vst.dylib
          asset_content_type: application/octet-stream
#      - name: Upload linux-x86_64 release artifact
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./linux-x86_64/librealearn.so
#          asset_name: realearn-linux-x86_64.so
#          asset_content_type: application/octet-stream